name: Run checks after pushing

on: [push]

jobs:
  run-checks:
    name: Run checks after commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "--version"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Run formatting checks
        run: ruff check
      - name: Install main dependencies
        run: |
          uv pip install --system -r requirements.txt
      - name: Install test depedencies
        run : |
          uv pip install --system pytest
      - name: Test with pytest
        env:
          TENNET_API_KEY: ${{ secrets.api_key }}
        run: |
          pytest
